### ISSUE TITLE
VHOST for osci.io with SAN

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker-infrastructure#17]
At this moment it is possible to read data from the new node via SSL, however, DNS resolution is a problem. To make it easier for everyone it would be better to create new virtual host for `osci.io`. So people can validate changes and status. For production, we will revoke certs + drop vhost.

So what we need is
- New VHOST osci.io
- New cert with SAN refers to beaker-project.org + beaker-project.osci.io

**Comment by duck-rh** [comment]
that was fixed a while ago.
