### ISSUE TITLE
Rebase playbooks to the latest available major version of Ansible

### ISSUE THREAD

**Issue by StykMartin** [beaker-project/beaker-infrastructure#36]
This codebase is quite outdated at this point.

We are quite far from the latest available Ansible, and it is likely that the toolchain will no longer work properly.
Rebase the playbooks and repository to the latest major release available and adjust the playbooks to work again.

**Comment by StykMartin** [comment]
@duck-rh can you take a look at this? We are planning to change some things in the infrastructure and this is the first step to get things going.

**Comment by duck-rh** [comment]
So I made changes to modernize and fix the run. It was not horribly obsolete; the major change was to use the new place for OSCI roles and take advantage of all the improvements that were done there. The switch to FQCN is not complete but there's no urgency and ansible-lint is happy at the moment. I'll continue improving the roles independently of the beaker work; most of them have tests and it's working too.

I think we're good here.
